### ISSUE TITLE
Viewer scrollbar on windows

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-ui#1101]
It seems that on Windows we have an horizontal scrollbar that doesn't appear on mac os.

Windows: 
<img width="609" alt="Capture d’écran 2019-07-11 à 10 02 31" src="https://user-images.githubusercontent.com/1107936/61033102-0509f680-a3c3-11e9-880e-80d5772ce3ce.png">

mac os : 
<img width="507" alt="Capture d’écran 2019-07-11 à 10 04 40" src="https://user-images.githubusercontent.com/1107936/61033236-51edcd00-a3c3-11e9-9b9a-f1961485e98b.png">

**Comment by GoOz** [comment]
Yeah, the horizontal bar appears because the vertical one is here.
On Windows, unlike Mac OS, the scrollbar push the content instead of going over it.

In your case, because it's an image or an object or whatever but not text, and since the container has a strict width, the content cannot be pushed, hence the horizontal scrollbar.

Unfortunately, I don't know any magic trick for that.

- You could add an `overflow-x: hidden` but the image would still be truncated by the vertical scrollbar.
- Another tricky way is to add a `padding-right` of  `15px` but still, if the user, let's say for accessibility reasons, has a bigger scrollbar, it would still truncate the content a little *and* this padding would always be here, even if there's no need for a scrollbar or for OS that don't "bug" like Windows do.
- Another way, a little more "bulletproof" would be to make sure that the container don't have a strict width but instead take 100% of the viewport's width, but in this case the vertical scrollbar would appear on the extreme right of the viewport instead of near the content.

**Comment by JF-Cozy** [comment]
@Ldoppea agreed
