### ISSUE TITLE
Transpiled components require to import utility css

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1119]
[In the docs](https://github.com/cozy/cozy-ui/#as-a-components-library), we say that:

> If you use the transpiled components (from cozy-ui/transpiled/react), you need to import the stylesheet (once):
> ```
> import Button from 'cozy-ui/transpiled/react/Button'
> import 'cozy-ui/transpiled/react/stylesheet.css'
> 
> <Button />
> ```
> You're now ready to use Cozy UI's (p)React components

But this promise is false: when using some components (for example `Caption`), some styles are not applied because the needed utility classes are not included in the transpiled stylesheet.

Here is a repro: https://codesandbox.io/s/charming-jones-ut5ro. On this sandbox, you can see that `Text` and `Caption` styles are totally missing. And some utility classes used by `Infos` are also missing. This means that the user is forced to import the utility css (https://github.com/cozy/cozy-ui/#utility-classes) to get working components.

I think the transpiled CSS should contain all the utility classes used by the react components. But I don't find why some utility classes are included  and others are not.

This problem is not visible in the styleguide, we found it in banks on the `Caption` component.

**Comment by drazik** [comment]
Actually some react components' styles import stylus files that import other stylus files that define global classes. For example `react/Panel/index.jsx` imports `react/Panel/styles.styl`, that imports `stylus/components/panels`, that imports `stylus/utilities/spaces.styl`. That's why we have spacing global utility classes available.

It means that all components that use global utility classes should import a stylus file that imports the stylus file containing the right utility classes.

**Comment by ptbrowne** [comment]
> I think the transpiled CSS should contain all the utility classes used by the react components.

Yes I agree.

> But I don't find why some utility classes are included and others are not.

<details>
<summary>For Text, its utility classes are not included in the stylesheet because Text is not `import`ing those styles. Click for more details ;)</summary>
The babel plugin (`css-modules-transform`) used to extract CSS to a separate stylesheet is based on JS imports of stylus files. Here is its config:

https://github.com/cozy/cozy-ui/blob/546c04b7fa99ad1ce3ad0f70ead3f64177dbf1ee/babel.config.js#L2-L10

Quick example:

`index.js`

```
import styles from './style.styl`

console.log(styles)
```

`style.styl`

```
.bg-red { background: red; }
.bg-blue { background: blue; }
```

goes through the babel with the `css-modules-transform`. `css-modules-transform` sees the `import` of a `styl` file. It compiles down the file to CSS module file and replaces the `import` by the object containing the classnames :

`index.transpiled.js`

```
// styles is not an import anymore, it is an object mapping "simple" class names to
// class names generated via CSS modules, according to the `generateScopedName` config
// attribute
const styles = {
  'bg-red': '.bg-red-347eqhiqw',
  'bg-blue '.bg-blue-347eqhiqw'
}

console.log(styles)
</details>

The solution would be to use class names from an `import` of styles. This way, `css-modules-transform` would be aware of the classes and would include them in the stylesheet.css.

**Comment by y-lohse** [comment]
> I think the transpiled CSS should contain all the utility classes used by the react components.

Yes definitely, the fact that it's not the case is a bug.

> The solution would be to use class names from an import of styles (instead of using global classes directly, from strings). 

That would work, including the solution highlighted below to minimize code duplication.

But we also had a discussion recently-ish about whether the transpiled stylesheet should also contain *all* utility classes (see [this issue](https://github.com/cozy/cozy-ui/issues/866)). There were arguments for and against it, but nothing too groundbreaking.  
However if we're going to import all utility classes anyway, we might as well expose them globally in the transpiled stylesheet (instead of running them through `css-module-transforms`). That way cozy-ui components can just use utility classes without worrying about importing them, and if an app imports the transpiled stylesheet, it automatically also has the utility classes. I would be more in favour of this solution. Any thoughts?

**Comment by ptbrowne** [comment]
Yes, having the utility classes in the stylesheet.css directly would be good also. I think this is simpler/better 👍

**Comment by drazik** [comment]
I agree :+1:
