### ISSUE TITLE
Spinner with color in CSS

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#121]
Right now you need to have one spinner per color. On `cozy-maif`, I removed the fill attribute on the SVG file to be able to color the spinner with `fill` in CSS. 

https://gitlab.cozycloud.cc/labs/cozy-maif/commit/826447c2e4f4e0670a93507a7aeb258a42d36105

What do you think of this approach ? I can make a PR.

**Comment by ptbrowne** [comment]
It can also be used with `fill: currentColor` so that the spinner automatically takes the color of the surrounding thex.

**Comment by m4dz** [comment]
IMHO, It works well if we don't use the spinner as a CSS background. @GoOz, can you confirm that this case never happens?

**Comment by gregorylegarec** [comment]
Seems like a great idea. We have already too much spinners.

**Comment by GoOz** [comment]
Every icon in Cozy-UI is used as a CSS background. Not that I absolulety want that but it's the way it works for now. I'd rather use SVG Sprite instead but that's not an easy work to refactor. There's a complex thinking to do here, because SVG Sprite is not the ultimate solution either (even if i do love that way ❤️ )

**Comment by ptbrowne** [comment]
OK so how can we move forward on this ?

**Comment by GoOz** [comment]
This should go with a update package about moving icon usage from CSS-background to SVG Sprite. This is clearly related to #130 & #125
