### ISSUE TITLE
Expanded click area for Icon with onClick prop ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-ui#1263]
In Banks we use a class that adds an invisible `:after` pseudo element
that helps to increase the clickable area of the Icon. Do you think
it would be a good idea to add this class automatically to Icons with 
an onClick property ?

One gotcha is that the Icon renders an `svg` element that cannot have
an `:after` element. In Banks we wrap the Icon with a span that has the
`u-expanded-click-area` class. Maybe we could have an Icon.Clickable
element ? I think it would be surprising if we'd wrap automatically the
svg in a span if the onClick prop is present, but I am interested of
what you think.

```
    // TODO Move utility to cozy-ui
    .u-expanded-click-area
      position relative
      display inline-block

    .u-expanded-click-area::after
      width 300%
      height 300%
      top -100%
      left -100%
      content '\00a0'
      display block
      position absolute
```

**Comment by Crash--** [comment]
> Do you think it would be a good idea to add this class automatically to Icons with an onClick property ? 

Definitively!

Today, we generally don't manage the click area on our mobile app / website and it can be pretty hard to click on it. We talked this use case with @joel-costa two weeks ago and the idea was to create an area about at least 48x48 px when we have a small icon. 

We just have to be careful and not apply a percentage or else because if we have a big icon, this area will be far too big

**Comment by y-lohse** [comment]
I personally rarely if ever use only an `Icon` component for something that can be clicked, and instead use the `iconOnly` variation of the `Button` component, which has a larger click area, and is also more semantic and accessible.  Do you have examples where an icon is clickable  but the `Button` component is not a good fit?

**Comment by ptbrowne** [comment]
Interesting. Which theme do you use for Buttons to be usable in a Row so that it is 48px*48px ?

<img width="248" alt="image" src="https://user-images.githubusercontent.com/465582/69525574-b1123f80-0f68-11ea-9b39-2ef7f1bbc5ed.png">

Here I tried to use the theme=`text` and with iconOnly=true.

```
<Button iconOnly={true} icon='cross' theme='text' />
```

**Comment by ptbrowne** [comment]
> We just have to be careful and not apply a percentage or else because if we have a big icon, this area will be far too big

Yes, this is why I wanted to discuss about this, I was wondering if we'd needed a u-click-48 class that would not be implemented via percentage but with `width: 48px; height: 48px`.

**Comment by y-lohse** [comment]
I've changed my mind about this, when implementing the Infos and InfosCarrousel there are times were a clickable Icon could have been a good fit.

So a few extra thoughts:

- if the icon is clickkable, we should wrap it in a `button` rather than a `span`
- Do we want the 48px size to be fixed ? It seems like quite a lot, I think most guidelines advocate for 40ish? cc @joel-costa 
- Do we want it to be invisible or part of the icon ? I think it should be invisible, but it also means that when several icons are next to each other, their click area might overlap…

**Comment by y-lohse** [comment]
Talking with @joel-costa 👍 

- Yes, always 48
- The click area should be "visible" and take it's own space

**Comment by Crash--** [comment]
48px since a good compromise (Apple recommends at least 40 and Google 48), but it should be definitely the minimum. 

On my previous app, we found out that 52px was better, but if I follow the recommendations of this article it should be 54 (https://medium.com/@zacdicko/size-matters-accessibility-and-touch-targets-56e942adc0cc) 

Also this article recommends to have at least 16 px between each touch targets

**Comment by ptbrowne** [comment]
Is there a UX guideline document where we can have this ?

**Comment by y-lohse** [comment]
I don't think we have such a document yet. Some usage rules are in the component documentation but that's kind of it. But maybe that's the right place for such a document anyway?

**Comment by ptbrowne** [comment]
IconButton can be used for those cases, I think we can close, feel free to re-open if needed.

**Comment by zatteo** [comment]
We got a feedback saying a 48x48 icon was too small which resulted in https://github.com/cozy/cozy-notes/pull/356

Maybe because there was no space between the icon and the containing area which was also a link.
