### ISSUE TITLE
Non-MUI components are not aware of theme

### ISSUE THREAD

**Issue by drazik** [cozy/cozy-ui#1333]
We now have two MUI theme variants: normal and inverted (see https://github.com/cozy/cozy-ui/pull/1317).

In https://github.com/cozy/cozy-keys-lib/pull/63 we had to play a lot with utility classes to change the color of some cozy-ui components to make it look good on primary color background (ie inverted theme). @ptbrowne suggested that our components could be aware of the theme and use different color according to the theme.

For now we have some kind of distinction between MUI and non-MUI components. The theme is clearly marked as "MUI". Maybe we should have a global theme that would be used for MUI and non-MUI components?

See comments on https://github.com/cozy/cozy-keys-lib/pull/63.

**Comment by edas** [comment]
I see 3 options : 


1. Let, step by step, allow UI components search their color and margin inside the MUI theme, and use an MUI theme to define the context for our React components

2. Create our own theme structure, inside cozy-UI, and let cozy-UI fill itself the MUI theme when the cozy-UI theme is changed / defined

3. Create an `<CozyInverted/>` or something like that, that swaps the CSS variables for the colors 

The 3rd option is very cheap and should work in most of simplier cases. If we want a full featured solution, I prefer the 2nd, at least because we still can swap our CSS variables without rewriting every component.

**Comment by y-lohse** [comment]
We agreed to go towards a mix of 2 and 3: Add a `CozyTheme` component that changes the value of the css color variables for it's children, and that also affects the Material UI theme. Feel free to take up this issue, especially if you need to introduce an `inverted` look for one of our existing components!

**Comment by ptbrowne** [comment]
A CozyTheme component has now been introduced :tada:
