### ISSUE TITLE
Viewer : argos test seems to be flaky

### ISSUE THREAD

**Issue by JF-Cozy** [cozy/cozy-ui#1839]
Voir par exemple la PR https://github.com/cozy/cozy-ui/pull/1837

Argos semble détecter des différence sur le Viewer alors qu'il n'y a aucun changement

**Comment by Crash--** [comment]
We just add another flaky comparaison. For the "MP3Viewer". It seems "normal" that this test is flaky since we really download the file to be able to play it. So depending on the bandwidth  the progress bar will not be the same 

<img width="1027" alt="Capture d’écran 2021-12-14 à 17 57 26" src="https://user-images.githubusercontent.com/1107936/146043748-1e172937-841e-49c9-aa34-71deb22c0c96.png">

**Comment by JF-Cozy** [comment]
Ce n'est plus le cas aujourd'hui
