### ISSUE TITLE
Generated CSS files are not optimized

### ISSUE THREAD

**Issue by Ldoppea** [cozy/cozy-ui#1991]
The way we generate CSS creates a lot of duplicated code.

For example if we open cozy-drive (on prod) and check the source for `/app/drive.<hash>.min.css`:
- `.CozyTheme--normal` and all its global vars is declared 9 times
- each declaration is suffixed with a hash so each one is targeting a single specific component

In theory CozyTheme should be declared only one time for all the app (or maybe 2 if the stack inject an override).

A possible side effect is if a component is targeted by `CozyTheme--normal--3iwbS` then is may be impossible to override its color from the stack?

Another example, if we open https://docs.cozy.io/cozy-ui/react/ and check the source for `/react/main.css`:
- the file is 34k lines of CSS
- `.u-pomegranate` is declared 17 times

However this second example seems to be specific to the documentation and does not appear in final applications

Let's discuss on how to optimize this.

**Comment by Crash--** [comment]
> A possible side effect is if a component is targeted by CozyTheme--normal--3iwbS then is may be impossible to override its color from the stack?

We don't override the className from the Stack. We override CSS values. And since `CozyTheme--normal` should only have CSS var declaration it should be fine ;)

**Comment by Crash--** [comment]
Also some thoughts about our CSS:
1/ We should remove the old cozy-ui.min.css. This one was useful when Cozy UI could be used as a vanilla CSS library. https://github.com/cozy/cozy-ui#as-a-vanilla-css-library It's not the case anymore and we should not produce this CSS file now. 
2/ CSS modules was used to scope our css instructions to be sure that each component is well isolated and we can't have side effect working on one. But since we tend to use CSS in JS with M-UI, I don't know if it's still needed in Cozy-UI ? 
3/ /transpiled/react/stylesheet.css contains all the CSS used by our React components. Even some of our utilities classes (it's enough to have a component using one utility class to have it in this file). So if an app import `stylesheet.css` and `cozy-ui.utils.min.css` then the app can load X times the same classes. 

If we take a look at the generated CSS from UI (https://unpkg.com/cozy-ui@58.1.2/transpiled/react/stylesheet.css & https://unpkg.com/cozy-ui@58.1.2/dist/cozy-ui.utils.min.css), and not from the app, then we can see that: 
- we have one `u-pomegranate` per file (so it's kinda OK minus the 3/)
- we have 16 times the declaration of `CozyTheme--normal_XXX` in `stylesheet.css`. After a quick check, it seems that we have that declaration for every component that require `settings/palette`? We have 14 `.styles__CozyTheme--normal--XXX` one `utils__CozyTheme--normal--XXX` and one `palette__CozyTheme--normal-XXX`

**Comment by Crash--** [comment]
Since we still thought about it this lunchtime... 

Having the `CozyTheme` (normal and inverted) with CSS modules break our override processus. In our themeoverride.css we'll target something like this: 

```css
::root {
primaryColor: 'red'
}

.CozyTheme--inverted {
primaryColor: 'blue'
}
```

But since React component use hashed classnames (aka cozyTheme--inverted-XXX), our override will not work.

**Comment by JF-Cozy** [comment]
see https://github.com/cozy/cozy-ui/pull/2454
