### ISSUE TITLE
Global styles

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#624]
Hi, we recently ran [into a problem](https://github.com/cozy/cozy-drive/pull/1200) where we needed to upgrade the cozy-bar in order to upgrade cozy-ui.

This is a problem because it effectively makes cozy-bar a dependency of cozy-ui, but the cozy-bar is a bit trickier to update — and really there's no reason for this dependency.

From what I understand, cozy-ui creates some global styles, and the cozy-bar injects these same global styles. Since the cozy-bar comes second, it overrides the styles from cozy-ui.

So I have a few questions:

1. First, is my understanding of the problem correct ?
2. Are there many of these global styles in cozy-ui ? What do they do ?
3. Why are these same styles injected by the cozy-bar ?

Looping in @GoOz and @CPatchane

**Comment by GoOz** [comment]
1. Yes
2. There's some yes. Utility classes, generic styles (default behavior and look for some HTML elements) mostly. 
3. Because the Cozy-bar needs some UI styles. I think it was decided this way to make sure that an app not using Cozy-UI but using the Cozy-bar would still get an clean & working Cozy-bar.

The thing is an app & the bar could need different versions of UI. We can't ensure those two to always be synced. Ideally we should have some kind of scope so the UI from the bar don't conflict with the one of the app. I'm not sure how yet. I thought about maybe "prefixing" every CSS selector with `[role=banner]` but it won't work for low level elements such as `html` or `body`.
Open to suggestions though.

**Comment by y-lohse** [comment]
Thanks for the answer!

> Ideally we should have some kind of scope so the UI from the bar don't conflict with the one of the app.

Yes, I agree! I think we shouldn't leak any css in the global scope by default, otherwise it sort of defeats the purpose of css modules. Are the global styles visible somewhere in the code base? And would it be realistic to remove them?

Maybe we can publish a second package, that would be based on cozy-ui, that creates these global styles, maybe with a collection of utility classes, etc. And if an app wants global styles, it can load them explicitly?

**Comment by GoOz** [comment]
I don't know… I was wondering on the other hand if there should be Cozy-UI in the Cozy-bar at all.

The "aria-hidden incident" revealed itself because we had twice the same library in the same page, if I put aside the fact that it's not a clever thing to do for performance, this seems the most important issue, more than the global styles that are kinda needed at the moment.

The cozy-bar needs UI for a few basic things: defaults, colors, fonts, icons, a dropdown menu and that's pretty much it. I guess there's something to do here.

**Comment by ptbrowne** [comment]
It seems to me a problem of the cozy-bar. It should not leak global styles if it only needs some styles from cozy-ui.

**Comment by ptbrowne** [comment]
Ping, @CPatchane do you have time to look at the issue ?

**Comment by CPatchane** [comment]
Not for now, and it has a low priority :/

**Comment by y-lohse** [comment]
See https://github.com/cozy/cozy-bar/pull/608
