### ISSUE TITLE
MenuItem icon alignment

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#654]
As part of an upcoming design, we need a `MenuItem` component, but with the icon being aligned at the top, and not in the middle, like this:

<img width="526" alt="capture d ecran 2018-10-19 18 15 23" src="https://user-images.githubusercontent.com/2261445/47230723-4c7ecb80-d3cb-11e8-8f12-4323378caf19.png">

I don't think this is supported at the moment? Is that something you could integrate in cozy-ui @GoOz ?

**Comment by GoOz** [comment]
Indeed, it's not supported yet.

**Comment by ptbrowne** [comment]
If there is no icon, `{ children }` is rendered, and then you can use your own custom `MenuItem` to have this behavior. It should be fairly easy with a `<Media />` and a `align='top'`
`MenuImg` should be exported so you can use it to have the right margin etc.. and probably a `MenuLegend` component.

It is not clear to me what should be the behavior in case of overflow of the label, if it gets on two lines. Should the icon be vertically aligned top with the label, or vertically aligned middle with the label ?
Since the alignment of the icon would be with the label and not with the menu item, I have trouble finding good prop names for the API, do you have anything in mind ?

**Comment by y-lohse** [comment]
@ptbrowne thanks for the tip! Definitely looks like it would work.

But after checking with @Claiw , it appears that the icon should *always* be aligned with the first line of content in a menu like that, and pretty much never been centered. So I think we should change the default behaviour here. The center-alignment could either be an option, or a custom implementation whenever someone needs it. If we want an option, we could go with `iconAlignment="top"`  and `iconAlignment="center"`?

**Comment by y-lohse** [comment]
Small misconception we just cleared up with @ptbrowne : aside from the icon alignment, we also need to be able to provide a "legend" for the label, which also needs customization options. 
So we'll probably do the whole work at once in the next couple of weeks (changing the defaults and adding the new sub-components.)
