### ISSUE TITLE
Spread props in Menu component (and onSelectDisabled warning)

### ISSUE THREAD

**Issue by cedricmessiant** [cozy/cozy-ui#898]
In [`Menu`](https://github.com/cozy/cozy-ui/tree/master/react/Menu) component, `restProps` are passed to the main `<div>`. It causes a warning because `onSelectDisabled` is not a valid event handler. Also we should avoid to use spread props (here I think we don't want to pass anything to the div (and the fact that we pass `onSelect` prop to the div may lead to strange bugs).

Could we just remove `{...restProps}` from the div ?

( Also, `onSelectDisabled` is supposed to be a `PropTypes.func` but its default prop is `null` (and a few props are missing from proptypes) )

**Comment by drazik** [comment]
I don't think removing props spreading is a good solution. DOM props should be spread, and non-DOM props should be destructured and carefuly applied where it makes sense. If `onSelectDisabled` is not destructured and applied to the good element, it may be because it's useless. I think looking at the usefulness of this prop and maybe removing or apply it to the good element is the best way to solve this issue.

**Comment by cedricmessiant** [comment]
In this case, it is not useless, just not used in `render()`. This props is used to define a different behaviour on click if the item is disabled. 
If we want to pass DOM props, we could either call this const `domProps` instead of `restProps` so that there is no ambiguity and maybe use something like [filter-react-dom-props](https://www.npmjs.com/package/filter-react-dom-props) to ensure we don't pass non DOM props to DOM components. A quick fix would be to destructure `onSelectDisabled` in render with an eslint-disable-line. Though, we should take a look at this `onSelect` prop that we probably don't want to pass to the `div` neither (it is in fact the `onClick` handler when the menu is not disabled)

**Comment by ptbrowne** [comment]
I am still hesitating on restProps. For wrapper classes that have only one underlying `div`, I think it makes senses to use `restProps`. Here I am more circumspect : there is the "control" div and the "menu" div so that it is unclear for the user on which div will be applied the `restProps`.

In Banks we do not use restProps so I think it would make sense to remove it.
I agree with the quick fix of destructuring non DOM properties.

**Comment by y-lohse** [comment]
I think the general rule @drazik mentioned is what we should follow. This seems to be an outlier, so the destructuring with the eslint is ok for me. If we end up having the same problem elsewhere, we can see about using a heavier solution like `domProps` or `filter-react-dom-props`.
