### ISSUE TITLE
Replace remaining embedurl

### ISSUE THREAD

**Issue by y-lohse** [cozy/cozy-ui#902]
We are using the stylus `embedurl` in a few places: https://github.com/cozy/cozy-ui/search?q=embedurl&unscoped_q=embedurl

The problem is that these embeds don't go through webpack, which makes them impossible to override in B2B theming. They also rely on a svg with a fixed color, making it cumbersome to support new colors for these icons.

 The replacement technique depends on the situation, but most of the time an `Icon` component is preferable.

**Comment by y-lohse** [comment]
This is nearly done. All "actual" icons are using the Icon component now, the checkboxes as well. AFAIL there's only the arrow for the select box that's still left. @GoOz can you confirm?

**Comment by GoOz** [comment]
Yeah. 
Basically it remains only in the code the embedurl icon for an `input[type=checkbox]` and a `select` but the React components `CheckBox` and `SelectBox` don't use that style (well it does but it overrides it mostly). So the migration shoud be easy. 
I left the old styles because it's still used and I can't change those styles without changing the DOM, also it allows having something consistent with the Cozy design guidelines when you're not using the React components with the default DOM for an `input[type=checkbox]` and a `select`, which the React components don't support.

**Comment by y-lohse** [comment]
Ok cool — so we have everything we need to have themed form components, it's just a matter of migrating. And we won't make a breaking change to force the migration at the moment, no rush 👍
